const i18Obj = {
  en: {
    skills: "Skills",
    portfolio: "Portfolio",
    video: "Video",
    price: "Price",
    contacts: "Contacts",
    "hero-title": "Alexa Rise",
    "hero-text":
      "Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise",
    hire: "Hire me",
    "skill-title-1": "Digital photography",
    "skill-text-1": "High-quality photos in the studio and on the nature",
    "skill-title-2": "Video shooting",
    "skill-text-2": "Capture your moments so that they always stay with you",
    "skill-title-3": "Rotouch",
    "skill-text-3": "I strive to make photography surpass reality",
    "skill-title-4": "Audio",
    "skill-text-4":
      "Professional sounds recording for video, advertising, portfolio",
    winter: "Winter",
    spring: "Spring",
    summer: "Summer",
    autumn: "Autumn",
    "price-descripton-1-span-1": "One location",
    "price-descripton-1-span-2": "120 photos in color",
    "price-descripton-1-span-3": "12 photos in retouch",
    "price-descripton-1-span-4": "Readiness 2-3 weeks",
    "price-descripton-1-span-5": "Make up, visage",
    "price-descripton-2-span-1": "One or two locations",
    "price-descripton-2-span-2": "200 photos in color",
    "price-descripton-2-span-3": "20 photos in retouch",
    "price-descripton-2-span-4": "Readiness 1-2 weeks",
    "price-descripton-2-span-5": "Make up, visage",
    "price-descripton-3-span-1": "Three locations or more",
    "price-descripton-3-span-2": "300 photos in color",
    "price-descripton-3-span-3": "50 photos in retouch",
    "price-descripton-3-span-4": "Readiness 1 week",
    "price-descripton-3-span-5": "Make up, visage, hairstyle",
    order: "Order shooting",
    "contact-me": "Contact me",
    "send-message": "Send message",
  },
  ru: {
    skills: "Навички",
    portfolio: "Портфоліо",
    video: "Відео",
    price: "Ціни",
    contacts: "Контакти",
    "hero-title": "Алекса Райс",
    "hero-text":
      "Збережіть емоції, романтичні переживання і щасливі моменти життя разом з професійним фотографом",
    hire: "Запросити",
    "skill-title-1": "Фотографія",
    "skill-text-1": "Високоякісні фото в студії та на природі",
    "skill-title-2": "Відеозйомка",
    "skill-text-2":
      "Зафіксуйте найкращі моменти, щоб вони завжди залишалися з вами",
    "skill-title-3": "Ретуш",
    "skill-text-3":
      "Я прагну до того, щоб  фотографія перевершувала реальність",
    "skill-title-4": "Звук",
    "skill-text-4": "Професійний запис звуку для відео, реклами, портфоліо",
    winter: "Зима",
    spring: "Весна",
    summer: "Літо",
    autumn: "Осінь",
    "price-descripton-1-span-1": "Одна локація",
    "price-descripton-1-span-2": "120 кольорових фото",
    "price-descripton-1-span-3": "12 отретушированих фото",
    "price-descripton-1-span-4": "Готовність через 2-3 тижні",
    "price-descripton-1-span-5": "Макіяж, візаж",
    "price-descripton-2-span-1": "Одна-дві локації",
    "price-descripton-2-span-2": "200 кольорових фото",
    "price-descripton-2-span-3": "20 отретушированих фото",
    "price-descripton-2-span-4": "Готовність через 1-2 тижні",
    "price-descripton-2-span-5": "Макіяж, візаж",
    "price-descripton-3-span-1": "Три локації та більше",
    "price-descripton-3-span-2": "300 кольорових фото",
    "price-descripton-3-span-3": "50 отретушированих фото",
    "price-descripton-3-span-4": "Готовність через 1 тиждень",
    "price-descripton-3-span-5": "Макіяж, візаж, зачіска",
    order: "Замовити зйомку",
    "contact-me": "Зв'яжіться зі мною",
    "send-message": "Відправити",
  },
};
export default i18Obj;
